# 工作流程名字
name: "构建"
# 触发工作流程事件
#on: [push]
on:
  push:
    branches:
      - master
# 流程子作业
jobs:
  java-build:
    runs-on: ubuntu-latest
    name: 检出项目1
    steps:
      - name: 检出项目2
        uses: actions/checkout@v3.2.0
        run: |
          ls ${{github.workspace}}
      - name: 检查环境
        run: |
          java -version \
          python version \
          node -v 

