# 工作流程名字
name: 项目构建
# 触发工作流程事件
#on: [push]
on:
  push:
    branches:
      - master
# 流程子作业
jobs:
  java-build:
    runs-on: ubuntu-latest
    name: 编译一个java项目
    steps:
      - name: 检出项目
        uses: actions/checkout@v3.2.0
      - name: 查看workspace
        run: |
          ls ${{github.workspace}}
      - name: 检查java环境
        run: |
          java -version \
      - name: 检查maven环境
        run: mvn -v
      - name: 检查仓库名字
        run: echo ${{ github.repository}}
      # - name: 开始打包
      #   run: mvn clean package -Dmaven.test.skip=true
      # - name: 发布包
      #   uses: actions/upload-artifact@v3.1.1
      #   with: 
      #     name: demo
      #     path: ${{ github.workspace }}/target/*.jar
      #     if-no-files-found: error