# 工作流程名字
name: "构建"
# 触发工作流程事件
#on: [push]
on:
  push:
    branches:
      - master
# 流程子作业
jobs:
  java-build:
    runs-on: ubuntu-latest
    name: 编译项目
    steps:
      - name: 检出项目
        uses: actions/checkout@v3.2.0
      - name: 查看workspace
        run: |
          ls ${{github.workspace}}
      - name: 检查java环境
        run: |
          java -version \
      - name: 检查maven环境
        run: mvn -v